#!/bin/sh

start()
{
    echo "Starting dashboard demo"

    # wait for the card to initialize
    #for i in `seq 1 3`;
    #do
	#res=$(cat /sys/class/drm/card0/*/modes 2>/dev/null | tr -d '\n')
	#[ -z "$res" ] || break
	#sleep 1
    #done

    while true; do
        cd /usr/bin
        egt_motorcycledash
    done &
}

stop()
{
    killall -9 egt_motorcycledash
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    *)
	;;
esac
