#!/bin/sh

start()
{
    echo "Starting Demo..."
       
    while true; do
        cd /usr/bin/
        egt_motorcycledash 
    done &
}

stop()
{
  killall -9 egt_motorcycledash
}


case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  *)
  ;;
esac
